var mongoose     = require('mongoose');
var Schema       = mongoose.Schema;

var TeamSchema     = new Schema({
	yearID:        {type: Number, required: true},
	lgID:          {type: String, required: true},
	teamID:        {type: String, required: true},
	franchID:      {type: String,},
	divID:         {type: String, required: true},
	Rank:          {type: String},
	G:             {type: Number},
	Ghome:         {type: Number},
	W:             {type: Number},
	L:             {type: Number},
	DivWin:        {type: Number},
	WCWin:         {type: Number},
	LgWin:         {type: Number},
	WSWin:         {type: Number},
	R:             {type: Number},
	AB:            {type: Number},
	H:             {type: Number},
	'2B':          {type: Number},
	'3B':          {type: Number},
	HR:            {type: Number},
	BB:            {type: Number},
	SO:            {type: Number},
	SB:            {type: Number},
	CS:            {type: Number},
	HBP:           {type: Number},
	SF:            {type: Number},
	RA:            {type: Number},
	ER:            {type: Number},
	ERA:           {type: Number},
	CG:            {type: Number},
	SHO:           {type: Number},
	SV:            {type: Number},
	IPouts:        {type: Number},
	HA:            {type: Number},
	HRA:           {type: Number},
	BBA:           {type: Number},
	SOA:           {type: Number},
	E:             {type: Number},
	DP:            {type: Number},
	FP:            {type: Number},
	name:          {type: String},
	park:          {type: String},
	attendance:    {type: Number},
	BPF:           {type: Number},
	PPF:           {type: Number},
	teamIDBR:      {type: Number},
	created_at:    { type: Date, default: Date.now },
	updated_at:    { type: Date, default: Date.now }
});

module.exports = mongoose.model('Team', TeamSchema);